### ISSUE TITLE
Replace sidetiq with whenever gem

### ISSUE THREAD

**Issue by gaurav-teliax** [tfxc/issues#11]
We need to replace the `sidetiq` gem with `whenever` gem because, the `sidetiq` gem is no longer maintained. 

We need to replace all schedulable workers like billing and cdr uploads.

**Comment by pandurang90** [comment]
Here are other options available ontohub/ontohub#1529

**Comment by gaurav-teliax** [comment]
We have added the replacement as `sidekiq-cron` and deployed it. Closing the ticket.
