### ISSUE TITLE
[TFXC] Add monitoring and altering to CIC Service

### ISSUE THREAD

**Issue by gaurav-teliax** [tfxc/issues#16]
There was a ticket in the TollFree.Exchange that the customers were not receiving the 302 CIC code from TFXC instead the calls were getting rejected with a 503 Reject.

The reason this happened is because, the CIC service process on the production instance, `cic-service-prod01` had stopped. We need to do . a couple things
- Investigate why the process stopped working and wasn't restarted
- Add monitoring and Alerting so that people can be notified if the service goes down.

**Comment by chungimo** [comment]
Looks like yum update was called and might have restarted some things - it didn't appear that cic_dip_service was enabled to start. systemctl enable cic_dip_service has now been ran to keep it enabled on system restart.

Modified /etc/systemd/system/cic_dip_service.service to include:
  Restart=on-failure
  RestartSec=5s

Created a cron job to watch for the process just in case - will report to slack in the event of total failure.
