### ISSUE TITLE
[Admin] Add Admin User management to Views 

### ISSUE THREAD

**Issue by gaurav-teliax** [tfxc/issues#17]
Right now we add AdminUsers in the exchange through the rails console or a task. We don't have UI for it. So on the views console we the admin users CRUD can be managed. 

There is a model in the views `Admin` where the admin users' records are. In the admin section of views we need to add UI so that the admin users can create, update, view and delete the users in the admin section. 

_Note. The admin_users table and model are different from the regular users._

**Comment by gaurav-teliax** [comment]
@bhartis007: There are a couple additions we need to make:
- We need a way to add Admin users. We don't need registrations for Admin users.
- The admin user should be able to update their information and change their password. I guess only change password exists right now.

**Comment by rshawnkeller** [comment]
users are unable to update company name, etc. in the web portal.

**Comment by rshawnkeller** [comment]
Closed per meeting with Shaun and Christy (6/30/2020)
