### ISSUE TITLE
[CDR Export] Enhancements

### ISSUE THREAD

**Issue by gaurav-teliax** [tfxc/issues#22]
We need to add a couple of enhancements CDR Export report. Please see the checklist
TODOs:
- [ ] Add appropriate indexes to the cdr's table
- [ ] Update the query timeout to 90 seconds
- [ ] Check if while uploading the CDRs there is a way in Google storage to compress the file

**Comment by pandurang90** [comment]
Here is the approach that we are going to use for optimizing reports,
1. Make api request to big query to execute call records query. This is an asynchronous operation. This will create a temporary table in bigquery.
2. Once query execution is over we will make another API request to export a temporary table created in step 1 to a compressed file and upload it to google storage.

**Comment by daldworth** [comment]
Will you need to perform any clean up steps? Does the temp table expire
automatically or is that a separate call?

**Comment by pandurang90** [comment]
We don't need to perform any cleanup steps. Temporary table has a lifetime of approximately 24 hours and also there are no charges on storing that. Here is more info on that https://cloud.google.com/bigquery/docs/writing-results
