### ISSUE TITLE
[Reporting][CDR] Duration calculation on CDRs

### ISSUE THREAD

**Issue by gaurav-teliax** [tfxc/issues#26]
This is more an investigative task than a code change. I am adding it here for tracking purposes. Aaron from Logmein wants to know how the duration calculation on a CDR happens. @pandurang90 we need to confirm this for @daldworth.

For Aaron's task we have the following fields from the CDR table:
1. `start_stamp`
1. `progress_stamp`
1. `answer_stamp`
1. `end_stamp`

@pandurang90: can we confirm for @daldworth that when the `duration` for the CDR is calculated we use the following logic:
```RUBY
if progress_stamp.present? then
  duration = end_stamp - progress_stamp
elsif preogress_stamp.blank? and answer_stamp.present? then 
  duration = end_stamp - answer_stamp
else(No progress_stamp and answer_stamp)
  duration = 0
end
```
If we can let @daldworth know the algorithm he will respond to Aaron accordingly

**Comment by pandurang90** [comment]
@gaurav-teliax Yes. The logic that you have mentioned is what we are using to calculate duration.

cc: @daldworth

**Comment by gaurav-teliax** [comment]
This has been verified. Closing the ticket.
