### ISSUE TITLE
Remove auto-notification for ALL PARTNERS when a ROID is activated on the platform.   

### ISSUE THREAD

**Issue by rshawnkeller** [tfxc/issues#34]
Current Behavior:  Notification from NoReply@Tollfree.exchange is sent to the TFX email contact list every-time a new ROID is activated on the Exchange Platform.  In times of bulk additions, these emails can become overwhelming and feel very "spam like".  These notifications do not provide a way for our Partners to opt-out.

Preferred Behavior:  Notification of all new ROID additions be emailed once daily to an internal TFX distro list.  List TBD

**Comment by rshawnkeller** [comment]
Shaun T. Moore
the priority here is to stop notifications to partners.
If we can then add a subset distro at a set  interval (i.e. daily, weekly etc) and combine all new add notifications to a single notification that includes a list of all adds during that interval, that would be great.  
If both can be done as one project without delaying it, that would be fine, but stopping the notices is the need.

**Comment by CarlsBad505** [comment]
@rshawnkeller can we get an example of what the email looks like uploaded here?

**Comment by suraiyarahmet** [comment]
Do not know what distro list this pulls from. Notification is also believed to be the same for Partners:

![image (4)](https://user-images.githubusercontent.com/18103890/85889352-e9a12280-b7b0-11ea-89be-81b5ee2c4dad.png)

**Comment by CarlsBad505** [comment]
thank you @suraiyarahmet

**Comment by CarlsBad505** [comment]
**Technical Background:**

The place where this is happening is in the `ResporgAccountId` model. There is an after update callback method `change_status_for_trunk_details` that fires these notifications off when the instance is verified and active. If these conditions are met, we then proceed to loop through all the associated resporgs and email them this notification.

**Solutions:**
1) Its easy to just stop emailing the resporgs. This can be accomplished quickly

2) To put these into a distro list and delay the emails to just batch send once a day, this is much bigger effort and deserves its own ticket. This is what would need to be done:
- Store a list of recipients and a hash of the instance data needed to send the email. This would be stored in something like Redis for example so we can pull down this list later.
- Create a sidekiq job to execute this once per day.
- Write specs
- Delete Redis record(s) once complete with daily job.

@rshawnkeller thoughts?

**Comment by CarlsBad505** [comment]
Add blocked label until we talk to Shaun about these options listed above

**Comment by rshawnkeller** [comment]
> @rshawnkeller can we get an example of what the email looks like uploaded here?

I do not.  Will need to wait until our meeting with Shaun M.

**Comment by rshawnkeller** [comment]
Step 1: Disable all emails.
Step 2: Create a daily/weekly digest that consolidates all notifications into a single email.
Step 3. Allow granularity of amount of email notifications going out. (opt in/opt out)

**Comment by CarlsBad505** [comment]
relates to issue #39

**Comment by CarlsBad505** [comment]
The scope of this ticket is now to just remove the notifications for resporg partners. I linked another issue for the longer term solution. I am also going to change the points for this ticket due to the scope change.
