### ISSUE TITLE
Enhancement Request: Additional Fields/Mappings for TollFree.Exchange generated CDRs

### ISSUE THREAD

**Issue by teliaxdavec** [tfxc/issues#41]
Adding additional fields to the TFX Platform CDR’s
Part One: Adding/modifying Originating Telephone number fields
Part Two: Adding Pseudo Jip fields

**PART ONE**
As a Toll-Free Exchange Partner I want to be able to view the P-Charge field, the P-Asserted field and the Called From field within the TFX CDR’s so that I can capture the correct “originating Telephone Number” on my CDR’s regardless of the method used by the originating carrier (P-charge, P-Asserted, From).

Note: All data for TFX CDR’s is pulled from data in Big Query

Currently the TFX CDR has a “Called From” field that is mapped from the P-asserted field in the call record. If the Originating Partner does not use the P-Asserted field, then the “Called From” field on the CDR is left blank.

**Requested Behavior:** 

We would like to add two fields to the existing TFX CDR’s and change the current mapping of the existing “Called From” field.

1. Add field: P-Charge and map from the P-charge in call record
2. Add Field: P-Asserted and map from the P-Asserted field in call record
3. Update existing “Called From” field to map from the “From” field in the call record.

Example One: Current Fields

![exampleone](https://user-images.githubusercontent.com/28909043/89206146-10a00080-d576-11ea-9a73-800a97823886.png)

 
Example Two: Additional fields added

![example2](https://user-images.githubusercontent.com/28909043/89206159-172e7800-d576-11ea-8bb9-67b9def3d606.png)

 Column D:
Field Name: P-Charge
Field Mapping from BQ: PCI (P-Charge)
Column E:
 Field Name: P-Asserted
 Field Mapping from BQ: P-Asserted
Column F:
 Field Name: No Change (Called From)
 Field Mapping from BQ: From (current mapping = P-Asserted)

**PART TWO**
MOVED to https://github.com/tfxc/issues/issues/44

**Comment by CascadiaSnow** [comment]
We have discovered that the Platform is using the P-charge field behind the scenes to rate calls. when the field is available in the call info.   Without this information being available on the CDR, it causes great confusion as it is very hard to determine why a call may have failed.  Having correct and complete CDRs is imperative.  Please consider this issue to be URGENT!  Thank you.

**Comment by CarlsBad505** [comment]
For informational purposes, the Call Records data in Google Big Query is originated from pcap data. One can access pcap data from a tool called WireShark (Christy and Patrice both use this, maybe others too). Example of pcap data for a call is shown in the screen shot below:

![image (1).png](https://images.zenhubusercontent.com/5eab2b9f1e31bd010da5e432/71c3cc46-8072-403c-a100-0c7e65e6462d)

**Comment by suraiyarahmet** [comment]
Approved. CDRs are being mapped as desired. 

![CDRsConfirmation.gif](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/de9d1d21-2196-4501-ba0b-fc651a0591b7)

![Screen Shot 2020-09-08 at 2.28.17 PM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/bb5bc12c-3bc0-4002-9ddb-de8df65a625a)

![Screen Shot 2020-09-08 at 2.58.33 PM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/5538472d-aba5-4636-a278-3c24a690688c)
