### ISSUE TITLE
Summary Table needed for Quick Books Reporting

### ISSUE THREAD

**Issue by stacey-carmel** [tfxc/issues#7]
I need a way to pull the following information for Quick Books Reporting.  
Please create a summary table of cached information from the actual invoices.
I will only report this monthly, so I think if we  only keep 3 months rolling at a time, that will be fine.

The following fields are needed:
Customer Name  - and how this was received.  I assume it came from a list of RespOrgs?
Invoice Date
Invoice Number
Due Date
Terminating Activity and its price
Originating Activity and its price
Toll-Free Exchange Fee and its price

**Comment by gaurav-teliax** [comment]
Query is passed on to Stacey.
